### ISSUE TITLE
egl and glx backends linux nvidia 590.44.01 driver sometimes don't repaint when should and window starts toggling between 2 frames when repaint happens outside it

### ISSUE THREAD

**Issue by xBZZZZ** [yshui/compton#1488]
## nvidia bug report: https://forums.developer.nvidia.com/t/picom-sometimes-doesnt-repaint-gtk-3-with-nvidia-driver-590-44-01/355216

https://github.com/user-attachments/assets/07b71460-880a-44b5-b781-bee7837f1daf

toggling between 2 frames also happens without [mangohud](https://software.opensuse.org/download/package?package=mangohud&project=openSUSE%3AFactory) and `--monitor-repaint`

picom version: https://github.com/yshui/picom/commit/800421acd4bc65b5de2fd29bf49279aa44026256

also notice how at 00:05 in video `Terminal Preferences` switched to `Colors` tab same frame that `xclock` seconds diamond moved, that is not because I clicked at same time as seconds changed but because there was delay between me clicking and `Colors` tab showing

with nvidia driver 580.105.08 picom worked normally(ish)

**Comment by yshui** [comment]
if downgrading the driver fixes it then it is a driver bug. most likely NVIDIA messed up their buffer age query somehow.

**Comment by xBZZZZ** [comment]
> most likely NVIDIA messed up their buffer age query

I assume you are talking about whatever this function is doing:https://github.com/yshui/picom/blob/800421acd4bc65b5de2fd29bf49279aa44026256/src/backend/gl/egl.c#L295-L304<sup>why does github prepend space to every line?</sup>

if I run `picom --backend=egl --no-use-damage` command line argument, `egl_buffer_age` is never called and there is no toggling between 2 frames but there is still sometimes delay between me clicking and `Shortcuts` tab showing

https://github.com/user-attachments/assets/8ef6915e-8eeb-40ac-9347-f8f534048c97

(using `xclock -norender -update 10` instead of `xclock -norender -update 1` to make delay longer and obvious)

also gpu is NVIDIA GeForce GTX 1660

**Comment by yshui** [comment]
> I assume you are talking about whatever this function is doing:

yes. if `--no-use-damage` didn't fix it, it is _even less likely_ this is our problem.

i recommend you report this to nvidia.

**Comment by raven2cz** [comment]
@xBZZZZ I’m just asking, is it possible to link this here with the upstream issue? So we know the current status here. Picom can’t really be used at all right now with this bug.

**Comment by yshui** [comment]
This seems to also affect 580.119.02 (#1489)

**Comment by yshui** [comment]
In the meantime, is downgrading the driver not an option?

**Comment by xBZZZZ** [comment]
https://forums.developer.nvidia.com/t/picom-sometimes-doesnt-repaint-gtk-3-with-nvidia-driver-590-44-01/355216

**Comment by yshui** [comment]
@xBZZZZ thank you!

**Comment by pjanx** [comment]
And 590.48.01 with RTX 4090 behaves the same.

**Comment by fengwk** [comment]
same issues

```
~ > yay -Q|grep nvidia                                                                                       at 01:34:15
lib32-nvidia-utils 590.48.01-1
libnvidia-container 1.18.1-1
linux-firmware-nvidia 20251125-2
nvidia-container-toolkit 1.18.1-1
nvidia-open-lts 1:590.48.01-3
nvidia-settings 590.48.01-1
nvidia-utils 590.48.01-1

~ > nvidia-smi                                                                                               at 01:34:31
Wed Dec 24 01:34:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0  On |                  N/A |
|  0%   43C    P5             41W /  390W |    1488MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1026      C   ...rog/ComfyUI/.venv/bin/python3        256MiB |
|    0   N/A  N/A            1978      G   /usr/lib/Xorg                           559MiB |
|    0   N/A  N/A            4162      G   /usr/bin/kitty                          137MiB |
|    0   N/A  N/A            7895      G   /usr/bin/kitty                           33MiB |
|    0   N/A  N/A           11353      G   ...ess --variations-seed-version          8MiB |
|    0   N/A  N/A           36380      G   ...rack-uuid=3190708988185955192        370MiB |
|    0   N/A  N/A           44631      G   /usr/bin/kitty                           52MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by cr4i50n** [comment]
> same issues
> 
> ```
> ~ > yay -Q|grep nvidia                                                                                       at 01:34:15
> lib32-nvidia-utils 590.48.01-1
> libnvidia-container 1.18.1-1
> linux-firmware-nvidia 20251125-2
> nvidia-container-toolkit 1.18.1-1
> nvidia-open-lts 1:590.48.01-3
> nvidia-settings 590.48.01-1
> nvidia-utils 590.48.01-1
> 
> ~ > nvidia-smi                                                                                               at     01:34:31
> Wed Dec 24 01:34:47 2025       
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
> +-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0  On |                  N/A |
> |  0%   43C    P5             41W /  390W |    1488MiB /  24576MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> 
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> |    0   N/A  N/A            1026      C   ...rog/ComfyUI/.venv/bin/python3        256MiB |
> |    0   N/A  N/A            1978      G   /usr/lib/Xorg                           559MiB |
> |    0   N/A  N/A            4162      G   /usr/bin/kitty                          137MiB |
> |    0   N/A  N/A            7895      G   /usr/bin/kitty                           33MiB |
> |    0   N/A  N/A           11353      G   ...ess --variations-seed-version          8MiB |
> |    0   N/A  N/A           36380      G   ...rack-uuid=3190708988185955192        370MiB |
> |    0   N/A  N/A           44631      G   /usr/bin/kitty                           52MiB |
> +-----------------------------------------------------------------------------------------+
> ```

a complete rollback to 

```
❯ cat /etc/pacman.d/mirrorlist
Server=https://archive.archlinux.org/repos/2025/10/21/$repo/os/$arch
```
with pacman -Syyuu solved the problem on Archlinux.


```
❯ nvidia-smi
Wed Dec 24 00:05:18 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        On  |   00000000:07:00.0  On |                  N/A |
| 30%   34C    P8             11W /  295W |     851MiB /  10240MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1279      G   /usr/lib/Xorg                           383MiB |
|    0   N/A  N/A            1288      G   picom                                    67MiB |
|    0   N/A  N/A            1794      G   alacritty                                10MiB |
|    0   N/A  N/A            2206      G   /usr/lib/electron37/electron             78MiB |
|    0   N/A  N/A            2458      G   alacritty                                10MiB |
|    0   N/A  N/A            2601    C+G   ...rack-uuid=3190708988185955192        193MiB |
+-----------------------------------------------------------------------------------------+

```

**Comment by yshui** [comment]
it would be more effective to reply to [the thread](https://forums.developer.nvidia.com/t/picom-sometimes-doesnt-repaint-gtk-3-with-nvidia-driver-590-44-01/355216) on nvidia's forum to let them know

@fengwk @pjanx

**Comment by cr4i50n** [comment]
> [@xBZZZZ](https://github.com/xBZZZZ) I’m just asking, is it possible to link this here with the upstream issue? So we know the current status here. Picom can’t really be used at all right now with this bug.

a workaround will be to switch to the xrender backend and enable use-ewmh-active-win = true; to get a somewhat working environment under picom, until nvidia hires some new, more "expensive" people (never).

https://github.com/NVIDIA/open-gpu-kernel-modules/issues/986#issuecomment-3692842042

**Comment by tcapd** [comment]
Following up on cr4i50n’s comment and yshui's question:
Downgrading NVIDIA driver from 580.119.02 to 580.95.05 solved the problem for me.

**Comment by chankongus** [comment]
If you are a poor soul that uses moldygreen gpus and wanted to know if 580.126.09 fixed anything, then no, certain pathetic multi-trillion dollar company didn't fix jacksh!t, this frameskipping in GTK still occurs.

**Comment by tofurky** [comment]
There is a response upstream saying they've identified the issue and it'll be fixed in an upcoming driver release: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/986#issuecomment-3861425530

**Comment by chankongus** [comment]
Don't bother. 580.126.18 didn't fix jackshit either. Stay at 580.105. There are even bigger GTK corruptions going on now, all my GTK windows are flickering like crazy. Most likely related to the fact that I'm stuck with nonGSP GTX1060 that can't run fixed open firmware. Utterly useless company.

**Comment by cr4i50n** [comment]
> Don't bother. 580.126.18 didn't fix jackshit either. Stay at 580.105. There are even bigger GTK corruptions going on now, all my GTK windows are flickering like crazy. Most likely related to the fact that I'm stuck with nonGSP GTX1060 that can't run fixed open firmware. Utterly useless company.

Call it indian expertise. Nvidia just as all other 'western' companies is 100% indian now and it shows.

**Comment by tcapd** [comment]
Edit: I tested 580.142, the problem is fixed in this version.

Linux x64 (AMD64/EM64T) Display Driver 580.142 | Linux 64-bit 

Quote:
Fixed a regression introduced in the 580.119.02 driver release which caused some X11 compositors (e.g. picom, Xfwm) to blink:     
https://github.com/NVIDIA/open-gpu-kernel-modules/issues/986        
https://github.com/yshui/picom/issues/1488

**Comment by chankongus** [comment]
Yep, it's fixed... {sigh} after 5 months. At least it's fixed.

**Comment by xBZZZZ** [comment]
nvidia driver 595.45.04 fixed
